openapi: 3.0.0
info:
  title: AI Icons API
  version: 1.0.0
paths:
  /:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eieshbjp15jf8vh9p0
        tag: "$latest"
        payload_format_version: "1.0"
      responses:
        default:
          description: Proxy response
  /{proxy+}:
    parameters:
      - name: proxy
        in: path
        required: true
        schema:
          type: string
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eieshbjp15jf8vh9p0
        tag: "$latest"
        payload_format_version: "1.0"
      responses:
        default:
          description: Proxy response
